name: CICD

on:
  push:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    name: app' tests
    steps:
      - uses: actions/checkout@v3
      - name: automated tests
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run test
